# Dockerfile.base
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

# 🔽 여기서 tensorflow-cpu를 2.10.1로 고정
RUN pip install pandas tensorflow-cpu==2.10.1
